version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile  # Adicione esta linha para usar o Dockerfile personalizado
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
  db:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example_root_password
      MYSQL_DATABASE: todo_db
      MYSQL_USER: todo_user
      MYSQL_PASSWORD: example_user_password
    volumes:
      - todo-data:/var/lib/mysql
volumes:
  todo-data: