version: '3'
services:
  web:
    image: php:apache
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example_root_password
      MYSQL_DATABASE: todo_db
      MYSQL_USER: todo_user
      MYSQL_PASSWORD: example_user_password
    volumes:
      - todo-data:/var/lib/mysql
volumes:
  todo-data: