version: '3'
services:
    web:
        build:
            context: docker
            dockerfile: Dockerfile
        ports:
            - "8080:80"
        volumes:
            - ./todo-app:/var/www/html
        depends_on:
            - db
        networks:
            rede:
    db:
        image: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: example_root_password
            MYSQL_DATABASE: todo_db
            MYSQL_USER: todo_user
            MYSQL_PASSWORD: example_user_password
        volumes:
            - todo-data:/var/lib/mysql
        restart: always
        networks:
            rede:
                ipv4_address: 10.5.0.10
volumes:
    todo-data:

networks:
    rede:
        driver: bridge
        ipam:
            config:
                -   subnet: 10.5.0.0/16